#!/usr/bin/env tsx
/**
 * Build the cross-link concept graph from content/lld/concepts/*.yaml.
 *
 * Emits src/lib/lld/concept-graph.ts — a typed, committed source file
 * with three maps:
 *   - conceptToPatterns: conceptId → patternSlug[]
 *   - patternToConcepts: patternSlug → Concept[]
 *   - conceptToRelated:  conceptId → conceptId[]
 *   - patternConfusedWith: patternSlug → [{ patternSlug, reason }]
 *
 * Runtime cost = zero DB calls; all lookups are O(1) on Maps.
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, basename } from "node:path";
import yaml from "js-yaml";
import type { ConceptYAML } from "../src/lib/lld/lesson-types";

const CONCEPT_DIR = "content/lld/concepts";
const OUTPUT = "src/lib/lld/concept-graph.ts";

interface ConceptEntry {
  id: string;
  label: string;
  summary: string;
}

interface GraphData {
  conceptToPatterns: Record<string, string[]>;
  patternToConcepts: Record<string, ConceptEntry[]>;
  conceptToRelated: Record<string, string[]>;
  patternConfusedWith: Record<
    string,
    Array<{ patternSlug: string; reason: string }>
  >;
}

async function main() {
  const graph: GraphData = {
    conceptToPatterns: {},
    patternToConcepts: {},
    conceptToRelated: {},
    patternConfusedWith: {},
  };

  if (!existsSync(CONCEPT_DIR)) {
    console.warn(
      `[build-concept-graph] ${CONCEPT_DIR} missing — writing empty graph`,
    );
  } else {
    const files = (await readdir(CONCEPT_DIR)).filter((f) =>
      f.endsWith(".concepts.yaml"),
    );

    for (const file of files) {
      const slug = basename(file, ".concepts.yaml");
      const raw = await readFile(join(CONCEPT_DIR, file), "utf8");
      const data = yaml.load(raw) as ConceptYAML;

      graph.patternToConcepts[slug] = (data.concepts ?? []).map((c) => ({
        id: c.id,
        label: c.label,
        summary: c.summary,
      }));

      for (const concept of data.concepts ?? []) {
        (graph.conceptToPatterns[concept.id] ??= []).push(slug);
        if (concept.relatedConcepts) {
          (graph.conceptToRelated[concept.id] ??= []).push(
            ...concept.relatedConcepts,
          );
        }
      }

      if (data.confusedWith) {
        graph.patternConfusedWith[slug] = data.confusedWith;
      }
    }
  }

  // Dedupe related concept arrays
  for (const id of Object.keys(graph.conceptToRelated)) {
    graph.conceptToRelated[id] = Array.from(
      new Set(graph.conceptToRelated[id]),
    );
  }

  const header = `/**
 * AUTO-GENERATED by scripts/build-concept-graph.ts.
 * Do not edit by hand. Re-run \`pnpm build:concept-graph\`.
 */

import type { ConceptYAML } from "./lesson-types";

export interface ConceptEntry {
  id: string;
  label: string;
  summary: string;
}

export type PatternConfusedWith = NonNullable<ConceptYAML["confusedWith"]>;

export const conceptToPatterns: Record<string, readonly string[]> = ${JSON.stringify(
    graph.conceptToPatterns,
    null,
    2,
  )};

export const patternToConcepts: Record<string, readonly ConceptEntry[]> = ${JSON.stringify(
    graph.patternToConcepts,
    null,
    2,
  )};

export const conceptToRelated: Record<string, readonly string[]> = ${JSON.stringify(
    graph.conceptToRelated,
    null,
    2,
  )};

export const patternConfusedWith: Record<string, PatternConfusedWith> = ${JSON.stringify(
    graph.patternConfusedWith,
    null,
    2,
  )};

export function getConceptsForPattern(slug: string): readonly ConceptEntry[] {
  return patternToConcepts[slug] ?? [];
}

export function getPatternsForConcept(conceptId: string): readonly string[] {
  return conceptToPatterns[conceptId] ?? [];
}

export function getRelatedConcepts(conceptId: string): readonly string[] {
  return conceptToRelated[conceptId] ?? [];
}

export function getConfusedWith(patternSlug: string): PatternConfusedWith {
  return patternConfusedWith[patternSlug] ?? [];
}
`;

  await writeFile(OUTPUT, header, "utf8");
  console.log(
    `[build-concept-graph] wrote ${OUTPUT} — ${
      Object.keys(graph.patternToConcepts).length
    } patterns, ${Object.keys(graph.conceptToPatterns).length} concepts`,
  );
}

main().catch((err) => {
  console.error("[build-concept-graph] fatal:", err);
  process.exit(1);
});
