/**
 * AUTO-GENERATED by scripts/build-concept-graph.ts.
 * Do not edit by hand. Re-run `pnpm build:concept-graph`.
 */

import type { ConceptYAML } from "./lesson-types";

export interface ConceptEntry {
  id: string;
  label: string;
  summary: string;
}

export type PatternConfusedWith = NonNullable<ConceptYAML["confusedWith"]>;

export const conceptToPatterns: Record<string, readonly string[]> = {};

export const patternToConcepts: Record<string, readonly ConceptEntry[]> = {};

export const conceptToRelated: Record<string, readonly string[]> = {};

export const patternConfusedWith: Record<string, PatternConfusedWith> = {};

export function getConceptsForPattern(slug: string): readonly ConceptEntry[] {
  return patternToConcepts[slug] ?? [];
}

export function getPatternsForConcept(conceptId: string): readonly string[] {
  return conceptToPatterns[conceptId] ?? [];
}

export function getRelatedConcepts(conceptId: string): readonly string[] {
  return conceptToRelated[conceptId] ?? [];
}

export function getConfusedWith(patternSlug: string): PatternConfusedWith {
  return patternConfusedWith[patternSlug] ?? [];
}
