// ─────────────────────────────────────────────────────────────
// PDF Export (EXP-008)
// Minimal PDF generator using browser APIs only.
// Converts the React Flow canvas to a PNG, then embeds it in a
// hand-crafted PDF binary stream.  No external dependencies.
// ─────────────────────────────────────────────────────────────

import { exportToPNG, blobToDataURL } from './to-png';
import type { PNGExportOptions } from './to-png';

// ── Page dimensions (points — 1 pt = 1/72 inch) ─────────────

const PAGE_SIZES = {
  a4: { width: 595.28, height: 841.89 },
  letter: { width: 612, height: 792 },
} as const;

type PageSize = keyof typeof PAGE_SIZES;

/** Options for PDF export. */
export interface PDFExportOptions {
  /** Title shown on the cover page (default: 'Architex Diagram'). */
  title?: string;
  /** Use landscape orientation (default: auto-detect from aspect ratio). */
  landscape?: boolean;
  /** Page size (default: 'a4'). */
  pageSize?: PageSize;
  /** PNG export options forwarded to the rasteriser. */
  pngOptions?: PNGExportOptions;
}

// ── Helpers ──────────────────────────────────────────────────

/**
 * Decode a base-64 data-URL into raw bytes and its MIME type.
 */
function decodeDataURL(dataURL: string): { bytes: Uint8Array; mime: string } {
  const [header, base64] = dataURL.split(',');
  const mime = header.match(/:(.*?);/)?.[1] ?? 'image/png';
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return { bytes, mime };
}

/**
 * Load an image from a data-URL and resolve its natural dimensions.
 */
function getImageDimensions(
  dataURL: string,
): Promise<{ width: number; height: number }> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () =>
      resolve({ width: img.naturalWidth, height: img.naturalHeight });
    img.onerror = () => reject(new Error('Failed to decode image dimensions.'));
    img.src = dataURL;
  });
}

// ── Minimal PDF builder ──────────────────────────────────────

/**
 * Build a minimal, valid PDF/1.4 binary from a PNG image.
 *
 * The generated file contains:
 *   1. A title page with diagram name and timestamp.
 *   2. The diagram image scaled to fit the page.
 *
 * This is intentionally spartan — enough for any PDF viewer to
 * open and render correctly, without dragging in jsPDF or pdfkit.
 */
function buildPDF(
  imageBytes: Uint8Array,
  imageDims: { width: number; height: number },
  options: Required<
    Pick<PDFExportOptions, 'title' | 'landscape' | 'pageSize'>
  >,
): Uint8Array {
  const basePage = PAGE_SIZES[options.pageSize];
  const pageW = options.landscape ? basePage.height : basePage.width;
  const pageH = options.landscape ? basePage.width : basePage.height;

  // Margins
  const margin = 40;
  const usableW = pageW - margin * 2;
  const usableH = pageH - margin * 2;

  // Scale the image to fit the usable area while preserving aspect ratio
  const imgAspect = imageDims.width / imageDims.height;
  const areaAspect = usableW / usableH;
  let drawW: number;
  let drawH: number;
  if (imgAspect > areaAspect) {
    drawW = usableW;
    drawH = usableW / imgAspect;
  } else {
    drawH = usableH;
    drawW = usableH * imgAspect;
  }

  // Centre the image on the page — PDF y-axis starts at the bottom
  const imgX = margin + (usableW - drawW) / 2;
  const imgY = margin + (usableH - drawH) / 2;

  // ── PDF objects ────────────────────────────────────────────
  // Object numbering starts at 1.  We track byte offsets for xref.

  const objects: string[] = [];
  const offsets: number[] = []; // byte offset of each object

  function addObj(content: string): number {
    const num = objects.length + 1;
    objects.push(`${num} 0 obj\n${content}\nendobj\n`);
    return num;
  }

  // 1 — Catalog
  const catalogObj = addObj(`<< /Type /Catalog /Pages 2 0 R >>`);

  // 2 — Pages tree (two pages: title + diagram)
  const pagesObj = addObj(
    `<< /Type /Pages /Kids [3 0 R 5 0 R] /Count 2 >>`,
  );

  // 3 — Title page
  addObj(
    [
      `<< /Type /Page /Parent ${pagesObj} 0 R`,
      `   /MediaBox [0 0 ${pageW} ${pageH}]`,
      `   /Contents 4 0 R`,
      `   /Resources << /Font << /F1 7 0 R >> >> >>`,
    ].join('\n'),
  );

  // 4 — Title page content stream
  const timestamp = new Date().toLocaleString();
  const titleEscaped = options.title
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
  const titleStream = [
    `BT`,
    `/F1 24 Tf`,
    `${margin} ${pageH - margin - 30} Td`,
    `(${titleEscaped}) Tj`,
    `0 -36 Td`,
    `/F1 12 Tf`,
    `(Exported: ${timestamp}) Tj`,
    `0 -24 Td`,
    `(Generated by Architex) Tj`,
    `ET`,
  ].join('\n');
  addObj(
    `<< /Length ${titleStream.length} >>\nstream\n${titleStream}\nendstream`,
  );

  // 5 — Diagram page
  addObj(
    [
      `<< /Type /Page /Parent ${pagesObj} 0 R`,
      `   /MediaBox [0 0 ${pageW} ${pageH}]`,
      `   /Contents 6 0 R`,
      `   /Resources << /XObject << /Img 8 0 R >> >> >>`,
    ].join('\n'),
  );

  // 6 — Diagram page content stream
  const diagramStream = [
    `q`,
    `${drawW} 0 0 ${drawH} ${imgX} ${imgY} cm`,
    `/Img Do`,
    `Q`,
  ].join('\n');
  addObj(
    `<< /Length ${diagramStream.length} >>\nstream\n${diagramStream}\nendstream`,
  );

  // 7 — Font (built-in Helvetica — no embedding needed)
  addObj(
    `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`,
  );

  // 8 — Image XObject (PNG stored as a DCT-free stream with FlateDecode
  //     fallback; we embed raw bytes and mark it as an "Image" with
  //     /Filter [] so viewers decode the PNG natively).
  //     Many viewers accept a PNG stream when the filter is omitted.
  //     For maximum compatibility we use /Filter /FlateDecode with the
  //     raw deflate stream from the PNG, but the simplest portable
  //     approach is to embed the entire PNG and tell the viewer to
  //     treat it as raw RGB.  Here we take the pragmatic route and
  //     inline the full PNG binary — all modern PDF viewers handle this.
  const imgObjHeader = [
    `<< /Type /XObject /Subtype /Image`,
    `   /Width ${imageDims.width} /Height ${imageDims.height}`,
    `   /ColorSpace /DeviceRGB /BitsPerComponent 8`,
    `   /Length ${imageBytes.length}`,
    `   /Filter /DCTDecode >>`,
  ].join('\n');

  // ── We need to inject raw binary for the image, so we build
  //    the final PDF byte-by-byte from here.

  const encoder = new TextEncoder();

  // Assemble text portion of PDF (header + objects 1-7)
  const header = `%PDF-1.4\n%\xE2\xE3\xCF\xD3\n`;
  const textParts: string[] = [header];

  for (const obj of objects) {
    offsets.push(
      textParts.reduce((a, s) => a + encoder.encode(s).length, 0),
    );
    textParts.push(obj);
  }

  // Object 8 (image) — mixed text + binary
  const imgObjNum = objects.length + 1; // 8
  const preImageText = textParts.join('');
  const preImageBytes = encoder.encode(preImageText);

  const imgHeaderStr = `${imgObjNum} 0 obj\n${imgObjHeader}\nstream\n`;
  const imgFooterStr = `\nendstream\nendobj\n`;
  const imgHeaderBytes = encoder.encode(imgHeaderStr);
  const imgFooterBytes = encoder.encode(imgFooterStr);

  // Record offset for object 8
  offsets.push(preImageBytes.length);

  // Build xref table
  const xrefOffset =
    preImageBytes.length +
    imgHeaderBytes.length +
    imageBytes.length +
    imgFooterBytes.length;

  const xrefLines = [`xref`, `0 ${imgObjNum + 1}`, `0000000000 65535 f \r`];
  for (const off of offsets) {
    xrefLines.push(`${String(off).padStart(10, '0')} 00000 n \r`);
  }

  const trailer = [
    `trailer`,
    `<< /Size ${imgObjNum + 1} /Root ${catalogObj} 0 R >>`,
    `startxref`,
    `${xrefOffset}`,
    `%%EOF`,
    ``,
  ].join('\n');

  const xrefAndTrailer = encoder.encode(xrefLines.join('\n') + '\n' + trailer);

  // Concatenate all parts into a single Uint8Array
  const totalLength =
    preImageBytes.length +
    imgHeaderBytes.length +
    imageBytes.length +
    imgFooterBytes.length +
    xrefAndTrailer.length;

  const pdf = new Uint8Array(totalLength);
  let pos = 0;

  pdf.set(preImageBytes, pos);
  pos += preImageBytes.length;

  pdf.set(imgHeaderBytes, pos);
  pos += imgHeaderBytes.length;

  pdf.set(imageBytes, pos);
  pos += imageBytes.length;

  pdf.set(imgFooterBytes, pos);
  pos += imgFooterBytes.length;

  pdf.set(xrefAndTrailer, pos);

  return pdf;
}

// ── Public API ───────────────────────────────────────────────

/**
 * Export the React Flow canvas as a PDF Blob.
 *
 * Converts the canvas to a high-resolution PNG first, then wraps
 * it in a minimal PDF structure with a title page.
 */
export async function exportToPDF(
  options?: PDFExportOptions,
): Promise<Blob> {
  const title = options?.title ?? 'Architex Diagram';
  const pageSize = options?.pageSize ?? 'a4';

  // Generate a high-res PNG of the canvas
  const pngBlob = await exportToPNG(options?.pngOptions ?? { scale: 2 });
  const dataURL = await blobToDataURL(pngBlob);
  const { width: imgW, height: imgH } = await getImageDimensions(dataURL);

  // Auto-detect orientation from image aspect ratio unless overridden
  const landscape = options?.landscape ?? imgW > imgH;

  // For DCTDecode we need JPEG bytes — re-render via canvas
  const jpegDataURL = await convertToJPEG(dataURL, imgW, imgH);
  const { bytes } = decodeDataURL(jpegDataURL);

  const pdf = buildPDF(bytes, { width: imgW, height: imgH }, {
    title,
    landscape,
    pageSize,
  });

  return new Blob([pdf.buffer as ArrayBuffer], { type: 'application/pdf' });
}

/**
 * Convert a PNG data-URL to a JPEG data-URL via an offscreen canvas.
 * DCTDecode (JPEG) is the simplest image format that every PDF viewer
 * supports without additional filters.
 */
function convertToJPEG(
  pngDataURL: string,
  width: number,
  height: number,
): Promise<string> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext('2d');
      if (!ctx) {
        reject(new Error('Failed to create canvas context for JPEG conversion.'));
        return;
      }
      // White background so transparency becomes white
      ctx.fillStyle = '#ffffff';
      ctx.fillRect(0, 0, width, height);
      ctx.drawImage(img, 0, 0);
      resolve(canvas.toDataURL('image/jpeg', 0.92));
    };
    img.onerror = () => reject(new Error('Failed to load image for JPEG conversion.'));
    img.src = pngDataURL;
  });
}

/**
 * Export the canvas as PDF and trigger a browser download.
 *
 * @param filename - download filename (default "architex-diagram.pdf")
 * @param options  - optional PDF export options
 */
export async function downloadPDF(
  filename?: string,
  options?: PDFExportOptions,
): Promise<void> {
  const blob = await exportToPDF(options);
  const url = URL.createObjectURL(blob);

  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename ?? 'architex-diagram.pdf';
  document.body.appendChild(anchor);
  anchor.click();

  // Cleanup
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}
