// -----------------------------------------------------------------
// Architex -- Graph Algorithms Barrel Export
// -----------------------------------------------------------------

import type { AlgorithmConfig } from '../types';

export type { GraphNode, GraphEdge, Graph, GraphElementState } from './types';

export { bfs } from './bfs';
export { dfs } from './dfs';
export { dfsIterative } from './dfs-iterative';
export { dijkstra } from './dijkstra';
export { kruskal } from './kruskal';
export { topologicalSort } from './topological-sort';
export { topologicalSortKahn } from './topological-sort-kahn';
export { bellmanFord } from './bellman-ford';
export { aStar } from './a-star';
export { tarjanSCC } from './tarjan-scc';
export { prims } from './prims';
export { floydWarshall } from './floyd-warshall';
export { bipartiteCheck } from './bipartite';
export { cycleDetection } from './cycle-detection';
export { eulerPath } from './euler-path';
export { fordFulkerson } from './ford-fulkerson';
export { articulationPoints } from './articulation-points';
export { bridges } from './bridges';

export {
  SIMPLE_UNDIRECTED,
  WEIGHTED_DIRECTED,
  DAG,
  CONNECTED_COMPONENTS,
  A_STAR_GRID,
  SCC_DIRECTED,
  BIPARTITE_GRAPH,
  CYCLE_DIRECTED,
  EULER_GRAPH,
  FLOW_NETWORK,
  ARTICULATION_BRIDGE_GRAPH,
  SAMPLE_GRAPH_FOR_ALGORITHM,
} from './sample-graphs';

/** Catalog of all graph algorithm configurations. */
export const GRAPH_ALGORITHMS: AlgorithmConfig[] = [
  {
    id: 'bfs',
    name: 'Breadth-First Search',
    category: 'graph',
    difficulty: 'beginner',
    timeComplexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)' },
    spaceComplexity: 'O(V)',
    description:
      'How does Facebook find people "2 connections away" from you? It uses BFS — explore all neighbors first (ring 1), then their unvisited neighbors (ring 2), like ripples from a stone in a pond. Uses a FIFO queue to guarantee shortest path in unweighted graphs. Used in: social networks, web crawlers, GPS, puzzle solvers. Remember: "Explore by rings. Queue = FIFO = nearest first."',
    complexityIntuition: 'O(V+E): visit every node once and traverse every edge once. Linear in the graph size.',
    realWorldApps: ['Social networks (degrees of separation)', 'Web crawlers', 'GPS shortest path (unweighted)'],
    interviewTips: "Asked at Google/Meta for shortest path. Key: always mention the QUEUE. Follow-up: 'BFS vs DFS -- when each?'",
    whenToUse: 'Use for shortest path in unweighted graphs or level-order traversal. Prefer DFS for topological sort or cycles.',
    comparisonGuide:
      'vs DFS: BFS finds shortest path in unweighted graphs; DFS uses less memory and is better for topological sort and cycle detection.',
    productionNote:
      'Web crawlers use priority-BFS with politeness delays, domain-level queues, and seen-URL Bloom Filters.',
    summary: [
      'Explore by rings (level by level). Uses a FIFO queue.',
      'O(V+E) time. Guarantees shortest path in unweighted graphs.',
      '"Drop a stone in a pond -- ripples spread outward."',
    ],
    commonMistakes: [
      '"BFS finds shortest path in weighted graphs" -- no! BFS only gives shortest path in UNWEIGHTED graphs.',
      '"BFS uses a stack" -- no! BFS uses a QUEUE (FIFO). DFS uses a stack.',
    ],
    pseudocode: [
      'procedure BFS(G, source)',
      '  for each vertex u in G do',
      '    color[u] = WHITE; dist[u] = INF',
      '  color[source] = GRAY; dist[source] = 0',
      '  enqueue(Q, source)',
      '  while Q is not empty do',
      '    u = dequeue(Q)',
      '    for each neighbor v of u do',
      '      if color[v] == WHITE then',
      '        color[v] = GRAY; dist[v] = dist[u] + 1',
      '        enqueue(Q, v)',
      '    color[u] = BLACK',
      '  return dist',
    ],
  },
  {
    id: 'dfs',
    name: 'Depth-First Search',
    category: 'graph',
    difficulty: 'beginner',
    timeComplexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)' },
    spaceComplexity: 'O(V)',
    description:
      'Imagine you\'re in a maze. You pick a corridor and follow it as far as you can. Dead end? Backtrack to the last fork and try another path. DFS dives deep before going wide, using a stack (or recursion) to remember where to backtrack. Ideal for cycle detection, topological sort, and connectivity. Used in: compiler dependency resolution, maze generation, garbage collection (mark-and-sweep). Remember: "Go deep, then backtrack. Stack = LIFO = deepest first."',
    complexityIntuition: 'O(V+E): same as BFS \u2014 every vertex and edge visited exactly once, just in depth-first order.',
    realWorldApps: ['Compiler dependency resolution', 'Maze generation', 'Garbage collection (mark-and-sweep)'],
    interviewTips: "Know recursive AND iterative (stack) forms. Follow-up: 'How do you detect cycles with DFS?' Gray/black coloring.",
    whenToUse: 'Use for cycle detection, topological sort, or exploring all paths. Prefer BFS for shortest path in unweighted graphs.',
    summary: [
      'Go as deep as possible, then backtrack. Uses a stack.',
      'O(V+E) time. Ideal for cycle detection and topo sort.',
      '"Maze runner" -- follow one path until stuck, then retreat.',
    ],
    commonMistakes: [
      '"DFS finds the shortest path" -- no! DFS finds A path, not the shortest. Use BFS for shortest.',
      '"DFS always uses recursion" -- you can implement DFS iteratively with an explicit stack.',
    ],
    pseudocode: [
      'procedure DFS(G)',
      '  for each vertex u in G do',
      '    color[u] = WHITE',
      '  time = 0',
      '  for each vertex u in G do',
      '    if color[u] == WHITE then',
      '      DFS-Visit(G, u)',
      'procedure DFS-Visit(G, u)',
      '  time++; discover[u] = time',
      '  color[u] = GRAY',
      '  for each neighbor v of u do',
      '    if color[v] == WHITE then',
      '      DFS-Visit(G, v)',
      '  color[u] = BLACK',
      '  time++; finish[u] = time',
    ],
  },
  {
    id: 'dfs-iterative',
    name: 'DFS (Iterative)',
    category: 'graph',
    difficulty: 'intermediate',
    prerequisites: ['dfs'],
    timeComplexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)' },
    spaceComplexity: 'O(V)',
    description:
      'Same traversal as recursive DFS but using an explicit stack — making the implicit call stack visible. Each pop() is like a function return. This variant avoids stack overflow on deep graphs and makes the stack data structure\'s role in DFS crystal clear.',
    complexityIntuition: 'O(V+E): identical to recursive DFS — every vertex and edge visited exactly once. The explicit stack just replaces the call stack.',
    realWorldApps: ['Deep graph traversal without stack overflow', 'Iterative deepening', 'Systems with limited call stack size'],
    interviewTips: "Interviewers love asking 'Can you convert this recursive DFS to iterative?' Know the stack-based pattern cold. Key insight: push neighbors in reverse order to match recursive traversal order.",
    whenToUse: 'Use when recursion depth could overflow the call stack (very deep graphs) or when you want explicit control over the traversal stack.',
    summary: [
      'Explicit stack replaces the call stack. push = recurse, pop = return.',
      'O(V+E) time, same as recursive. Avoids stack overflow on deep graphs.',
      '"Make the invisible visible" — the stack IS the DFS data structure.',
    ],
    commonMistakes: [
      '"Iterative DFS uses a queue" -- no! A queue gives BFS. DFS uses a STACK (LIFO).',
      '"Iterative and recursive DFS always visit in the same order" -- only if you push neighbors in reverse order.',
    ],
    pseudocode: [
      'procedure DFS-Iterative(G, source)',
      '  for each vertex u in G do',
      '    color[u] = WHITE',
      '  push source onto stack',
      '  while stack is not empty do',
      '    u = pop(stack)',
      '    if color[u] != WHITE then continue',
      '    color[u] = GRAY; time++; discover[u] = time',
      '    for each neighbor v of u (in reverse) do',
      '      if color[v] == WHITE then',
      '        push v onto stack',
      '    color[u] = BLACK; time++; finish[u] = time',
    ],
  },
  {
    id: 'dijkstra',
    name: "Dijkstra's Shortest Path",
    category: 'graph',
    difficulty: 'intermediate',
    prerequisites: ['bfs'],
    timeComplexity: {
      best: 'O((V + E) log V)',
      average: 'O((V + E) log V)',
      worst: 'O((V + E) log V)',
    },
    spaceComplexity: 'O(V)',
    description:
      'How does Google Maps find the fastest route to the airport? Dijkstra\'s algorithm, invented on a cafe napkin in 1956. Start at the source, always visit the closest unvisited node, update neighbor distances, repeat — spreading outward like a ripple. The greedy insight: the shortest known path to the nearest unvisited node IS the true shortest path. Used in: Google Maps, OSPF routing, game AI pathfinding. Remember: "Always visit the closest unvisited node. Spread like a ripple."',
    complexityIntuition: 'O((V+E) log V) with a binary heap. The log V comes from priority queue insert/extract operations.',
    realWorldApps: ['Google Maps routing', 'OSPF network protocol', 'Game AI pathfinding'],
    interviewTips: "Classic graph question. Know: fails with negative edges. Follow-up: 'What instead?' Bellman-Ford.",
    whenToUse: 'Use for shortest path with non-negative weights. Use Bellman-Ford for negatives. Floyd-Warshall for all-pairs.',
    comparisonGuide:
      "vs Bellman-Ford: Dijkstra is faster but can't handle negative edges. vs A*: A* is faster with a good heuristic. vs Floyd-Warshall: use FW for all-pairs.",
    productionNote:
      'Google Maps uses Contraction Hierarchies -- a precomputed shortcut graph that makes Dijkstra 1000x faster on road networks.',
    summary: [
      'Always visit closest unvisited node, update neighbor dists.',
      'O((V+E) log V) with heap. NON-NEGATIVE weights only.',
      '"Google Maps in an algorithm" -- spread from source like a ripple.',
    ],
    commonMistakes: [
      '"Dijkstra works with negative edges" -- no! Use Bellman-Ford for graphs with negative weights.',
      '"Dijkstra finds the path" -- it finds DISTANCES. Track "previous" pointers to reconstruct the path.',
    ],
    pseudocode: [
      'procedure Dijkstra(G, source)',
      '  for each vertex v in G do',
      '    dist[v] = INF; prev[v] = NIL',
      '  dist[source] = 0',
      '  PQ = all vertices with dist as key',
      '  while PQ is not empty do',
      '    u = extract-min(PQ)',
      '    for each neighbor v of u do',
      '      alt = dist[u] + weight(u, v)',
      '      if alt < dist[v] then',
      '        dist[v] = alt; prev[v] = u',
      '        decrease-key(PQ, v, alt)',
      '  return dist, prev',
    ],
  },
  {
    id: 'kruskal',
    name: "Kruskal's MST",
    category: 'graph',
    difficulty: 'intermediate',
    prerequisites: ['union-find'],
    timeComplexity: { best: 'O(E log E)', average: 'O(E log E)', worst: 'O(E log E)' },
    spaceComplexity: 'O(V)',
    description:
      'How would you connect all cities with the cheapest road network? Sort every possible road by cost, then keep adding the cheapest one that doesn\'t create a loop — that\'s Kruskal. Uses a Union-Find structure to detect cycles in near-constant time. Used in: network design, circuit wiring, clustering. Remember: "Sort all edges. Add cheapest. Skip if it loops."',
    realWorldApps: ['Network cable layout', 'Circuit wiring', 'Clustering algorithms'],
    interviewTips: "Know Union-Find inside out. Follow-up: 'Kruskal vs Prim -- when each?' Kruskal for sparse, Prim for dense.",
    whenToUse: 'Use for MST on sparse graphs. Prefer Prim for dense graphs or when you need to grow from a source.',
    summary: [
      'Sort all edges by weight, add cheapest that avoids cycles.',
      'O(E log E) time. Uses Union-Find for cycle detection.',
      '"Cheapest road network" -- greedy edge selection builds MST.',
    ],
    commonMistakes: [
      '"Kruskal always beats Prim" -- Prim is faster on dense graphs (adjacency matrix). Kruskal wins on sparse.',
      '"Kruskal works on directed graphs" -- MST is defined for undirected graphs only.',
    ],
    pseudocode: [
      "procedure Kruskal(G)",
      '  MST = empty set',
      '  sort edges by weight ascending',
      '  for each vertex v: make-set(v)',
      '  for each edge (u, v) in sorted order do',
      '    if find(u) != find(v) then',
      '      MST = MST + (u, v)',
      '      union(u, v)',
      '    else skip (would form cycle)',
      '  return MST',
    ],
  },
  {
    id: 'topological-sort',
    name: 'Topological Sort',
    category: 'graph',
    difficulty: 'intermediate',
    timeComplexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)' },
    spaceComplexity: 'O(V)',
    description:
      'In what order should you take university courses if some have prerequisites? Topological sort finds a valid sequence so every dependency is met before you reach the thing that needs it. Start with nodes that have zero prerequisites, remove them, repeat. Used in: build systems (Make/Bazel), package managers (npm install order), task scheduling. Remember: "No prerequisites left? You\'re next."',
    realWorldApps: ['Build systems (Make/Bazel)', 'npm install order', 'Course prerequisite planning'],
    interviewTips: "Know both Kahn's (BFS) and DFS approaches. Follow-up: 'What if there's a cycle?' No valid ordering exists.",
    whenToUse: 'Use when you need to order tasks with dependencies. Only works on DAGs (directed acyclic graphs).',
    pseudocode: [
      "procedure TopologicalSort(G)   // Kahn's algorithm",
      '  compute in-degree for each vertex',
      '  Q = all vertices with in-degree 0',
      '  order = empty list',
      '  while Q is not empty do',
      '    u = dequeue(Q)',
      '    append u to order',
      '    for each neighbor v of u do',
      '      in-degree[v]--',
      '      if in-degree[v] == 0 then',
      '        enqueue(Q, v)',
      '  if |order| != |V| then cycle detected',
      '  return order',
    ],
  },
  {
    id: 'topological-sort-kahn',
    name: "Topological Sort (Kahn's BFS)",
    category: 'graph',
    difficulty: 'intermediate',
    timeComplexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)' },
    spaceComplexity: 'O(V)',
    description:
      "While DFS-based topological sort uses recursion and a stack, Kahn's algorithm uses BFS: start with all nodes that have no incoming edges (in-degree 0), process them, reduce neighbors' in-degrees, enqueue newly-zero nodes. If the result has fewer nodes than the graph, there's a cycle. Used in: build systems (Make/Bazel), course scheduling, package managers.",
    complexityIntuition: 'O(V+E): each vertex is enqueued/dequeued once, and each edge is examined once when its source is processed.',
    realWorldApps: ['Build systems (Make/Bazel)', 'Course prerequisite scheduling', 'Package manager install order (npm, pip)'],
    interviewTips: "Know both Kahn's (BFS) and DFS approaches. Kahn's naturally detects cycles (output size < V). Follow-up: 'How do you get ALL valid topological orderings?'",
    whenToUse: "Use when you need to order tasks with dependencies. Only works on DAGs. Prefer Kahn's when you also need cycle detection.",
    pseudocode: [
      "procedure KahnTopologicalSort(G)  // BFS-based",
      '  for each vertex v in G do',
      '    compute in-degree[v]',
      '  Q = all vertices with in-degree 0',
      '  order = empty list',
      '  while Q is not empty do',
      '    u = dequeue(Q)',
      '    append u to order',
      '    for each neighbor v of u do',
      '      in-degree[v]--',
      '      if in-degree[v] == 0 then',
      '        enqueue(Q, v)',
      '  if |order| != |V| then cycle detected',
      '  return order',
    ],
  },
  {
    id: 'bellman-ford',
    name: 'Bellman-Ford Shortest Path',
    category: 'graph',
    difficulty: 'intermediate',
    prerequisites: ['dijkstra'],
    timeComplexity: { best: 'O(V * E)', average: 'O(V * E)', worst: 'O(V * E)' },
    spaceComplexity: 'O(V)',
    description:
      'Dijkstra fails on negative edges. What if your GPS could handle toll REBATES? Bellman-Ford relaxes every edge V-1 times, slowly converging on the true shortest paths even with negative weights. One extra pass detects negative cycles (free-money loops). Used in: currency arbitrage detection, network routing with variable costs. Remember: "Relax all edges V-1 times. One more pass catches negative cycles."',
    complexityIntuition: 'O(V\u00B7E): V-1 passes over all E edges. Slower than Dijkstra but handles negative weights.',
    realWorldApps: ['Currency arbitrage detection', 'Network routing (RIP protocol)', 'Constraint satisfaction'],
    interviewTips: "Know: detects negative cycles. Follow-up: 'Why V-1 relaxations?' Shortest path has at most V-1 edges.",
    whenToUse: 'Use when edges can have negative weights. Use Dijkstra if all weights are non-negative (faster).',
    summary: [
      'Relax every edge V-1 times; one more pass detects neg cycles.',
      'O(V*E) time. Handles negative weights unlike Dijkstra.',
      '"Currency arbitrage detector" -- finds free-money loops.',
    ],
    commonMistakes: [
      '"Bellman-Ford is slower, so never use it" -- it is the ONLY choice when negative edge weights exist.',
      '"V-1 passes is arbitrary" -- shortest path has at most V-1 edges, so V-1 relaxations suffice.',
    ],
    pseudocode: [
      'procedure BellmanFord(G, source)',
      '  for each vertex v in G do',
      '    dist[v] = INF; prev[v] = NIL',
      '  dist[source] = 0',
      '  for i = 1 to |V| - 1 do',
      '    for each edge (u, v, w) in G do',
      '      if dist[u] + w < dist[v] then',
      '        dist[v] = dist[u] + w; prev[v] = u',
      '  for each edge (u, v, w) in G do',
      '    if dist[u] + w < dist[v] then',
      '      report negative cycle',
      '  return dist, prev',
    ],
  },
  {
    id: 'a-star',
    name: 'A* Search',
    category: 'graph',
    difficulty: 'advanced',
    prerequisites: ['dijkstra'],
    timeComplexity: { best: 'O(E)', average: 'O(E log V)', worst: 'O(V^2)' },
    spaceComplexity: 'O(V)',
    description:
      'How do video game characters find the shortest path around obstacles? A* is Dijkstra with a compass — it adds a heuristic that estimates remaining distance to the goal, so it explores toward the destination instead of in all directions. With a good heuristic, it finds optimal paths while visiting far fewer nodes. Used in: game AI pathfinding, robot navigation, GPS routing. Remember: "Dijkstra + heuristic = search that looks where it\'s going."',
    complexityIntuition: 'O(E log V) avg with a good heuristic. Worst case O(V\u00B2) if heuristic is poor and graph is dense.',
    realWorldApps: ['Video game pathfinding', 'Robot navigation', 'GPS routing with heuristics'],
    interviewTips: "Know: admissible heuristic = never overestimates. Follow-up: 'What if h=0?' Degrades to Dijkstra.",
    whenToUse: 'Use when you have a good heuristic for the goal. Degrades to Dijkstra without one. Best for grid/map search.',
    pseudocode: [
      'procedure AStar(G, start, goal)',
      '  openSet = {start}; closedSet = {}',
      '  g[start] = 0',
      '  f[start] = h(start, goal)',
      '  while openSet is not empty do',
      '    current = node in openSet with lowest f',
      '    if current == goal then',
      '      return reconstruct_path()',
      '    move current from openSet to closedSet',
      '    for each neighbor v of current do',
      '      if v in closedSet then continue',
      '      tentative_g = g[current] + w(current, v)',
      '      if tentative_g < g[v] then',
      '        prev[v] = current',
      '        g[v] = tentative_g',
      '        f[v] = g[v] + h(v, goal)',
      '        add v to openSet',
      '  return failure (no path)',
    ],
  },
  {
    id: 'tarjan-scc',
    name: "Tarjan's SCC",
    category: 'graph',
    difficulty: 'advanced',
    timeComplexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)' },
    spaceComplexity: 'O(V)',
    description:
      'In a social network, which groups of people can ALL reach each other through follow chains? Tarjan\'s algorithm finds these clusters (SCCs) in a single DFS pass using a clever "lowlink" trick — tracking the earliest reachable ancestor on the stack. Used in: compiler optimization (dead code detection), dependency analysis, 2-SAT solvers. Remember: "One DFS. Track lowlinks. Pop a component when root found."',
    pseudocode: [
      'procedure Tarjan(G)',
      '  index = 0; S = empty stack',
      '  for each vertex v in G do',
      '    if v.index is undefined then',
      '      strongconnect(v)',
      'procedure strongconnect(v)',
      '  v.index = v.lowlink = index++',
      '  push v onto S; v.onStack = true',
      '  for each edge (v, w) do',
      '    if w.index is undefined then',
      '      strongconnect(w)',
      '      v.lowlink = min(v.lowlink, w.lowlink)',
      '    else if w.onStack then',
      '      v.lowlink = min(v.lowlink, w.index)',
      '  if v.lowlink == v.index then',
      '    pop SCC from stack until v',
      '    output SCC',
    ],
  },
  {
    id: 'prims',
    name: "Prim's MST",
    category: 'graph',
    difficulty: 'intermediate',
    timeComplexity: { best: 'O(E log V)', average: 'O(E log V)', worst: 'O(E log V)' },
    spaceComplexity: 'O(V + E)',
    description:
      'Kruskal sorts all edges globally. What if you grew the tree from one node instead, always picking the cheapest next connection? That\'s Prim\'s — start anywhere, add the cheapest edge connecting the tree to a non-tree node, repeat. Uses a priority queue to grab the minimum edge fast. Used in: network design, approximation algorithms for NP-hard problems. Remember: "Grow from one node. Always pick the cheapest bridge out."',
    pseudocode: [
      "procedure Prim(G, source)",
      '  for each vertex v: key[v] = INF; inMST[v] = false',
      '  key[source] = 0',
      '  PQ = min-priority queue of all vertices by key',
      '  while PQ is not empty do',
      '    u = extract-min(PQ)',
      '    inMST[u] = true',
      '    for each neighbor v of u do',
      '      if not inMST[v] and weight(u,v) < key[v] then',
      '        key[v] = weight(u,v); parent[v] = u',
      '        decrease-key(PQ, v)',
      '  return parent (MST edges)',
    ],
  },
  {
    id: 'floyd-warshall',
    name: 'Floyd-Warshall',
    category: 'graph',
    difficulty: 'advanced',
    timeComplexity: { best: 'O(V^3)', average: 'O(V^3)', worst: 'O(V^3)' },
    spaceComplexity: 'O(V^2)',
    description:
      'What\'s the shortest distance between EVERY pair of cities on a map? Floyd-Warshall answers this with a beautifully simple idea: for each node k, check if routing through k improves the path between every pair (i, j). Three nested loops, O(V^3), done. Used in: GPS precomputation, network routing tables, transitive closure. Remember: "For each middleman k, can i-k-j beat i-j directly?"',
    pseudocode: [
      'procedure FloydWarshall(G)',
      '  let dist[][] = INF for all (i,j)',
      '  for each edge (u,v,w): dist[u][v] = w',
      '  for each vertex v: dist[v][v] = 0',
      '  for k = 1 to |V| do',
      '    for i = 1 to |V| do',
      '      for j = 1 to |V| do',
      '        if dist[i][k] + dist[k][j] < dist[i][j] then',
      '          dist[i][j] = dist[i][k] + dist[k][j]',
      '  return dist',
    ],
  },
  {
    id: 'bipartite',
    name: 'Bipartite Check',
    category: 'graph',
    difficulty: 'intermediate',
    timeComplexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)' },
    spaceComplexity: 'O(V)',
    description:
      'Can you color a graph with only 2 colors so no neighbors share a color? BFS from any node, alternating colors layer by layer. If you ever find a neighbor already colored the same — it\'s not bipartite. This simple test reveals whether a graph can be split into two independent groups. Used in: job assignment, matching problems, conflict detection. Remember: "Alternate colors by layer. Same-color neighbor = not bipartite."',
    pseudocode: [
      'procedure IsBipartite(G, source)',
      '  for each vertex u in G do',
      '    color[u] = UNCOLORED',
      '  color[source] = RED; enqueue(Q, source)',
      '  while Q is not empty do',
      '    u = dequeue(Q)',
      '    for each neighbor v of u do',
      '      if color[v] == UNCOLORED then',
      '        color[v] = opposite(color[u])',
      '        enqueue(Q, v)',
      '      else if color[v] == color[u] then',
      '        return false  // conflict found',
      '  return true',
    ],
  },
  {
    id: 'cycle-detection',
    name: 'Cycle Detection (Directed)',
    category: 'graph',
    difficulty: 'intermediate',
    timeComplexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)' },
    spaceComplexity: 'O(V)',
    description:
      'Does this dependency graph have a circular dependency? DFS with three colors finds out: white (unvisited), gray (in the current path), black (fully explored). If you ever visit a gray node again, you\'ve found a cycle — a back edge to something still on your call stack. Used in: deadlock detection, build system validation, import cycle checks. Remember: "Gray meets gray = cycle. Three colors, one DFS pass."',
    pseudocode: [
      'procedure HasCycle(G)',
      '  for each vertex u in G do',
      '    color[u] = WHITE',
      '  for each vertex u in G do',
      '    if color[u] == WHITE then',
      '      if DFS-Visit(u) == true then',
      '        return true  // cycle found',
      '  return false',
      'procedure DFS-Visit(u)',
      '  color[u] = GRAY  // in current stack',
      '  for each neighbor v of u do',
      '    if color[v] == GRAY then',
      '      return true  // back edge = cycle',
      '    if color[v] == WHITE then',
      '      if DFS-Visit(v) then return true',
      '  color[u] = BLACK',
      '  return false',
    ],
  },
  {
    id: 'euler-path',
    name: "Euler Path (Hierholzer's)",
    category: 'graph',
    difficulty: 'advanced',
    timeComplexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)' },
    spaceComplexity: 'O(E)',
    description:
      'Can you walk every bridge in Konigsberg exactly once? Euler proved it impossible in 1736, founding graph theory. Hierholzer\'s algorithm solves the general case: follow edges greedily until stuck, then backtrack and splice in detours from unused edges. Works when 0 or 2 vertices have odd degree. Used in: circuit board routing, DNA fragment assembly, network inspection. Remember: "Follow until stuck. Backtrack and splice detours."',
    pseudocode: [
      "procedure Hierholzer(G, start)",
      '  check degree conditions for path/circuit',
      '  stack = [start]; circuit = []',
      '  while stack is not empty do',
      '    u = top of stack',
      '    if u has unused edges then',
      '      pick an unused edge (u, v)',
      '      mark edge as used',
      '      push v onto stack',
      '    else',
      '      pop u from stack',
      '      prepend u to circuit',
      '  return circuit',
    ],
  },
  {
    id: 'ford-fulkerson',
    name: 'Ford-Fulkerson (Edmonds-Karp)',
    category: 'graph',
    difficulty: 'expert',
    timeComplexity: { best: 'O(V * E^2)', average: 'O(V * E^2)', worst: 'O(V * E^2)' },
    spaceComplexity: 'O(V^2)',
    description:
      'What\'s the maximum water flow through a pipe network from reservoir to city? Find any path with spare capacity, push as much flow as possible, repeat. The Edmonds-Karp variant uses BFS to find the shortest augmenting path each time, guaranteeing polynomial termination. Used in: network bandwidth optimization, supply chain logistics, bipartite matching. Remember: "Find a path. Push flow. Repeat until no path remains."',
    pseudocode: [
      'procedure FordFulkerson(G, source, sink)',
      '  initialize residual graph from capacity edges',
      '  maxFlow = 0',
      '  while BFS finds augmenting path from source to sink do',
      '    bottleneck = min residual capacity along path',
      '    for each edge (u, v) on path do',
      '      residual[u][v] -= bottleneck',
      '      residual[v][u] += bottleneck',
      '    maxFlow += bottleneck',
      '  return maxFlow',
    ],
  },
  {
    id: 'articulation-points',
    name: 'Articulation Points',
    category: 'graph',
    difficulty: 'advanced',
    timeComplexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)' },
    spaceComplexity: 'O(V)',
    description:
      'Which server, if it crashes, splits your network into disconnected parts? Articulation points are those critical nodes. DFS tracks two values per node: discovery time and the lowest ancestor reachable ("lowlink"). If no descendant of a node can reach above it, removing it disconnects the graph. Used in: network reliability analysis, infrastructure planning. Remember: "If no child can reach above you, you\'re a single point of failure."',
    pseudocode: [
      'procedure FindArticulationPoints(G)',
      '  timer = 0',
      '  for each vertex v in G do',
      '    if v not visited then DFS(v, null)',
      'procedure DFS(u, parent)',
      '  disc[u] = low[u] = timer++',
      '  childCount = 0',
      '  for each neighbor v of u do',
      '    if v not visited then',
      '      childCount++; DFS(v, u)',
      '      low[u] = min(low[u], low[v])',
      '      if parent == null and childCount > 1 then',
      '        u is articulation point (root)',
      '      if parent != null and low[v] >= disc[u] then',
      '        u is articulation point',
      '    else if v != parent then',
      '      low[u] = min(low[u], disc[v])',
    ],
  },
  {
    id: 'bridges',
    name: 'Bridge Finding',
    category: 'graph',
    difficulty: 'advanced',
    timeComplexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)' },
    spaceComplexity: 'O(V)',
    description:
      'Which connection, if cut, disconnects part of your network? Bridges are those critical edges. Like articulation points, DFS tracks discovery time and lowlink values — but the condition is stricter: an edge (u, v) is a bridge only if NO vertex in v\'s subtree can reach u or above. Used in: critical infrastructure identification, network redundancy planning. Remember: "If the subtree can\'t reach back, cutting that edge splits the graph."',
    pseudocode: [
      'procedure FindBridges(G)',
      '  timer = 0',
      '  for each vertex v in G do',
      '    if v not visited then DFS(v, null)',
      'procedure DFS(u, parent)',
      '  disc[u] = low[u] = timer++',
      '  for each neighbor v of u do',
      '    if v not visited then',
      '      DFS(v, u)',
      '      low[u] = min(low[u], low[v])',
      '      if low[v] > disc[u] then',
      '        (u, v) is a bridge',
      '    else if v != parent then',
      '      low[u] = min(low[u], disc[v])',
    ],
  },
];
